library(ISLR)
data(Auto)
fit <- lm(mpg ~ horsepower, data = Auto)
summary(fit)
predict(fit, data.frame(horsepower = 98), interval = "confidence")
predict(fit, data.frame(horsepower = 98), interval = "prediction")
plot(Auto$horsepower, Auto$mpg, main = "Scatterplot of mpg vs. horsepower", xlab = "horsepower", ylab = "mpg", col = "blue")
abline(fit, col = "red")
par(mfrow = c(2, 2))
plot(fit)
pairs(Auto)
names(Auto)
cor(Auto[1:8])
fit2 <- lm(mpg ~ . - name, data = Auto)
summary(fit2)
par(mfrow = c(2, 2))
plot(fit2)
fit3 <- lm(mpg ~ cylinders * displacement+displacement * weight, data = Auto[, 1:8])
summary(fit3)
par(mfrow = c(2, 2))
plot(log(Auto$horsepower), Auto$mpg)
plot(sqrt(Auto$horsepower), Auto$mpg)
plot((Auto$horsepower)^2, Auto$mpg)
data(Carseats)
fit3 <- lm(Sales ~ Price + Urban + US, data = Carseats)
summary(fit3)
fit4 <- lm(Sales ~ Price + US, data = Carseats)
summary(fit4)
confint(fit4)
par(mfrow = c(2, 2))
plot(fit4)
